/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

/**
 *
 * @author Keith
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
    }
    
    // trivial cahnge to force repo update

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_matrixOne = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_matrixOneRows = new javax.swing.JTextField();
        lbl_matrixOneRows = new javax.swing.JLabel();
        lbl_matrixOneColumns = new javax.swing.JLabel();
        txt_matrixOneColumns = new javax.swing.JTextField();
        lbl_matrixOneValues = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tar_matrixOneValues = new javax.swing.JTextArea();
        btn_matrixOneAddValue = new javax.swing.JButton();
        btn_matrixOneAddRow = new javax.swing.JButton();
        pnl_matrixTwo = new javax.swing.JPanel();
        lbl_matrixTwo = new javax.swing.JLabel();
        lbl_matrixTwoRows = new javax.swing.JLabel();
        lbl_matrixTwoColumns = new javax.swing.JLabel();
        txt_matrixTwoRows = new javax.swing.JTextField();
        txt_matrixTwoColumns = new javax.swing.JTextField();
        lbl_matrixTwoValues = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tar_matrixTwoValues = new javax.swing.JTextArea();
        btn_matrixTwoAddValue = new javax.swing.JButton();
        btn_matrixTwoAddRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_matrixOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Matrix 1");

        txt_matrixOneRows.setMinimumSize(new java.awt.Dimension(60, 20));
        txt_matrixOneRows.setPreferredSize(new java.awt.Dimension(60, 20));

        lbl_matrixOneRows.setText("Number of Rows:");

        lbl_matrixOneColumns.setText("Number of Columns:");

        txt_matrixOneColumns.setPreferredSize(new java.awt.Dimension(60, 20));

        lbl_matrixOneValues.setText("Matrix 1 Values");

        tar_matrixOneValues.setEditable(false);
        tar_matrixOneValues.setColumns(20);
        tar_matrixOneValues.setRows(5);
        jScrollPane1.setViewportView(tar_matrixOneValues);

        btn_matrixOneAddValue.setText("Add Value");

        btn_matrixOneAddRow.setText("Add Row");

        javax.swing.GroupLayout pnl_matrixOneLayout = new javax.swing.GroupLayout(pnl_matrixOne);
        pnl_matrixOne.setLayout(pnl_matrixOneLayout);
        pnl_matrixOneLayout.setHorizontalGroup(
            pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_matrixOneLayout.createSequentialGroup()
                .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_matrixOneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(pnl_matrixOneLayout.createSequentialGroup()
                        .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_matrixOneLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(pnl_matrixOneLayout.createSequentialGroup()
                                        .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl_matrixOneLayout.createSequentialGroup()
                                                .addComponent(lbl_matrixOneRows)
                                                .addGap(24, 24, 24))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_matrixOneLayout.createSequentialGroup()
                                                .addComponent(lbl_matrixOneColumns)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_matrixOneRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_matrixOneColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_matrixOneAddValue)
                                            .addComponent(btn_matrixOneAddRow)))))
                            .addGroup(pnl_matrixOneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_matrixOneValues)))
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        pnl_matrixOneLayout.setVerticalGroup(
            pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_matrixOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matrixOneRows)
                    .addComponent(txt_matrixOneRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_matrixOneAddValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_matrixOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_matrixOneColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_matrixOneColumns)
                    .addComponent(btn_matrixOneAddRow))
                .addGap(18, 18, 18)
                .addComponent(lbl_matrixOneValues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_matrixOneRows.getAccessibleContext().setAccessibleDescription("");

        pnl_matrixTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_matrixTwo.setPreferredSize(new java.awt.Dimension(362, 344));

        lbl_matrixTwo.setText("Matrix 2");

        lbl_matrixTwoRows.setText("Number of Rows:");

        lbl_matrixTwoColumns.setText("Number of Columns:");

        txt_matrixTwoRows.setPreferredSize(new java.awt.Dimension(60, 20));

        txt_matrixTwoColumns.setPreferredSize(new java.awt.Dimension(60, 20));

        lbl_matrixTwoValues.setText("Matrix 2 Values");

        tar_matrixTwoValues.setEditable(false);
        tar_matrixTwoValues.setColumns(20);
        tar_matrixTwoValues.setRows(5);
        jScrollPane2.setViewportView(tar_matrixTwoValues);

        btn_matrixTwoAddValue.setText("Add Value");

        btn_matrixTwoAddRow.setText("Add Row");

        javax.swing.GroupLayout pnl_matrixTwoLayout = new javax.swing.GroupLayout(pnl_matrixTwo);
        pnl_matrixTwo.setLayout(pnl_matrixTwoLayout);
        pnl_matrixTwoLayout.setHorizontalGroup(
            pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_matrixTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnl_matrixTwoLayout.createSequentialGroup()
                        .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_matrixTwo)
                            .addGroup(pnl_matrixTwoLayout.createSequentialGroup()
                                .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_matrixTwoColumns)
                                    .addComponent(lbl_matrixTwoRows))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_matrixTwoRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_matrixTwoColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_matrixTwoAddRow)
                                    .addComponent(btn_matrixTwoAddValue)))
                            .addComponent(lbl_matrixTwoValues))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_matrixTwoLayout.setVerticalGroup(
            pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_matrixTwoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_matrixTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matrixTwoRows)
                    .addComponent(txt_matrixTwoRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_matrixTwoAddValue))
                .addGap(18, 18, 18)
                .addGroup(pnl_matrixTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matrixTwoColumns)
                    .addComponent(txt_matrixTwoColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_matrixTwoAddRow))
                .addGap(16, 16, 16)
                .addComponent(lbl_matrixTwoValues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_matrixTwoValues.getAccessibleContext().setAccessibleName("lbl_matrxiTwoValues");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_matrixOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_matrixTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_matrixTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_matrixOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_matrixOneAddRow;
    private javax.swing.JButton btn_matrixOneAddValue;
    private javax.swing.JButton btn_matrixTwoAddRow;
    private javax.swing.JButton btn_matrixTwoAddValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_matrixOneColumns;
    private javax.swing.JLabel lbl_matrixOneRows;
    private javax.swing.JLabel lbl_matrixOneValues;
    private javax.swing.JLabel lbl_matrixTwo;
    private javax.swing.JLabel lbl_matrixTwoColumns;
    private javax.swing.JLabel lbl_matrixTwoRows;
    private javax.swing.JLabel lbl_matrixTwoValues;
    private javax.swing.JPanel pnl_matrixOne;
    private javax.swing.JPanel pnl_matrixTwo;
    private javax.swing.JTextArea tar_matrixOneValues;
    private javax.swing.JTextArea tar_matrixTwoValues;
    private javax.swing.JTextField txt_matrixOneColumns;
    private javax.swing.JTextField txt_matrixOneRows;
    private javax.swing.JTextField txt_matrixTwoColumns;
    private javax.swing.JTextField txt_matrixTwoRows;
    // End of variables declaration//GEN-END:variables
}
